### ISSUE TITLE
intervals: provide facility to stop events firing

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/timer-adapter#10]
Use case: I have some lights in my living area that I want to have rules that involve both timers and intervals. The rules become prohibitively complex when mixing both, and would be vastly simpler if there was the ability to turn on/off the interval sending events.

This was previously available and was removed with the comment along the lines that it might be re-instated if someone provided a use-case. Hopefully, this is the use case :)

Expanding the use case: The timers are related to security, turning lights on for a number of minutes when the front door opens at night. The intervals are more related to entertainment, periodically changing the colours of the lights.

**Comment by tim-hellhake** [comment]
> Hopefully, this is the use case :)

Of course, if it really helps you ^^
I'm not at all against readding this.
I just prefer adding things when they are actually needed.
Still, I am curious in which case you need to use timers and intervals in the same rule.
If you use the timer to control the `on` property of the light and the interval to control the `color` property of the light, you would need to create separate rules.

**Comment by chas-iot** [comment]
I have no need to use both timers and intervals in the same rule. The issue is managing the interactions between rules, timers, intervals and their impact on the current state of the light.

BTW thank-you for the adaptor and on-going maintenance :)
