### ISSUE TITLE
on intervals, make the seconds property an option

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/timer-adapter#11]
Once an interval is integrated with rules, there's no need to display and update the seconds property. Why not make it an option whether the property is created and updated in the add-on settings?

I submitted https://github.com/tim-hellhake/timer-adapter/issues/9, which was related to this idea and was moved to the main gateway. However, I thought about it more and came up with this idea.

**Comment by tim-hellhake** [comment]
Did you have a chance to test it?

**Comment by chas-iot** [comment]
>
> Did you have a chance to test it?

Yes thanks, Tim :)
The updated driver is delivering events and is silent.
