### ISSUE TITLE
Add LevelProperty with the current number of seconds

### ISSUE THREAD

**Issue by tim-hellhake** [tim-hellhake/timer-adapter#2]
As proposed [here](https://github.com/tim-hellhake/counter-adapter/issues/2).

**Comment by tim-hellhake** [comment]
@Beejeedeb
Update is available.

**Comment by Beejeedeb** [comment]
Hi Tim,

Thanks for improving the timer.

But I encounter a problem with the timer add on after the Webthings update
to version 0.10 which is not solved by your update.  Old things cannot be
removed, new timers can be created, work well and can also be deleted.



Kind regards,

BJ
