### ISSUE TITLE
intervals not working with Mozilla Gateway 0.10?

### ISSUE THREAD

**Issue by cjcorrigan** [tim-hellhake/timer-adapter#5]
When I create an Interval in the add-on, then add it as a thing and then open the Interval on the things page, I no longer see the properties. And in the rules, the drop-down to set properties has no entries on an interval..

After upgrading the gateway, I was able to get Timers working by erasing all and re-creating. However, I have not managed to get Intervals working. I had an Interval working with gateway 0.9.2

**Comment by tim-hellhake** [comment]
Let me check that.

**Comment by tim-hellhake** [comment]
I created a new interval on a `0.10.0` gateway and it looks like this for me:

![image](https://user-images.githubusercontent.com/17127122/69151508-0bc81900-0adb-11ea-8cc6-b6ab7a41a113.png)

**Comment by tim-hellhake** [comment]
The rule looks like this:

![image](https://user-images.githubusercontent.com/17127122/69151689-65c8de80-0adb-11ea-9cdb-2a8e62820e17.png)

**Comment by tim-hellhake** [comment]
Did you also deleted and readded the intervals?

**Comment by cjcorrigan** [comment]
Yes I deleted and re-created the intervals.

Yesterday, an interval just appeared as a thing, with no properties. I could see the elapsed events being delivered. Today, it appears as a multi-level sensor with a seconds property (and the elapsed events).

What I don't see is a property to disable an interval, which I did have under 0.9.2 unless my memory has gone seriously wobbly.

**Comment by tim-hellhake** [comment]
> Today, it appears as a multi-level sensor with a seconds property (and the elapsed events).
 
Good, that means it's working properly.

> What I don't see is a property to disable an interval, which I did have under 0.9.2 unless my memory has gone seriously wobbly.

No, you are right there was a property for this.
I removed it because it turned out the same can be achieved much simpler by using the `and` operator of the rule system.
See [here](https://github.com/tim-hellhake/google-home-adapter/issues/3#issuecomment-536330436).
If you still need it I can add it again.

**Comment by tim-hellhake** [comment]
@cjcorrigan
Is everything working fine?

**Comment by tim-hellhake** [comment]
@cjcorrigan
I'm closing this now, if you have any problems, please let me know.
