### ISSUE TITLE
Timers Disconnected

### ISSUE THREAD

**Issue by lacojim** [tim-hellhake/timer-adapter#6]
Nearly everytime I reboot my gateway RPi4, all my timers come back ghosted (disconnected). The only way I can get them to un-ghost is to create a new timer and then add it. Then, all the timers are functional again. I then delete the newly created “test” timer and all stays well until the next reboot.

**Comment by tim-hellhake** [comment]
Thanks for reporting this issue!
That's not supposed to happen.
I'll try it out with my pi.

**Comment by tim-hellhake** [comment]
I think I found the issue.
The new update should be available as soon as the PR is merged.

**Comment by lacojim** [comment]
Now that was fast. Thank you! Seems to be working well now. It has survived several reboots in a row, several minutes apart. If that should change, I will be sure to post here.

**Comment by lacojim** [comment]
Something I just noticed, every timer count is logged. I don't recall seeing this happen before. Seems to eat up a lot of unnecessary space.

**Comment by tim-hellhake** [comment]
> Now that was fast. Thank you! Seems to be working well now. It has survived several reboots in a row, several minutes apart. If that should change, I will be sure to post here.

I'm glad that everything works now :)
If you have any further problems just create an issue and I will try to fix it.

> I don't recall seeing this happen before. Seems to eat up a lot of unnecessary space.

The logs were already present in the old version.
I can add a debug log option in the settings to activate them only on purpose.

**Comment by lacojim** [comment]
> > Now that was fast. Thank you! Seems to be working well now. It has survived several reboots in a row, several minutes apart. If that should change, I will be sure to post here.
> 
> I'm glad that everything works now :)
> If you have any further problems just create an issue and I will try to fix it.
> 
> > I don't recall seeing this happen before. Seems to eat up a lot of unnecessary space.
> 
> The logs were already present in the old version.
> I can add a debug log option in the settings to activate them only on purpose.

That would be perfect. I have many timers and some are for very long times (30 to 120 minutes). Seems to fill up logs rather quickly when logging every second from 9 timers, not to mention potential overhead.. Thanks!

**Comment by lacojim** [comment]
I see you have now added the debug log in v1.3.0. Thank you so much. This will be quite useful in preventing my logs from approaching huge sizes.

**Comment by lacojim** [comment]
It does work, but it works the opposite of what I would think, When the Debug is checked, I do not see the timers in the log, when unchecked, I do. I can live with it for sure. Not a big deal.
