### ISSUE TITLE
Support shorter timer intervals than 1s

### ISSUE THREAD

**Issue by rmeissn** [tim-hellhake/timer-adapter#8]
I own a roller shutter, which is able to let a specific level of light into the room by opening it for a specific time interval after it was closed.
Example:
1. Roller shutter closes within 50s - fully dark now
2.1. E.g. roller shutter opens from 1. for 0.5s - half light
2.2. E.g. roller shutter opens from 1. for 1s - full light
3. Roller shutter opens for 50s - roller shutter is not closed anymore

I used your timers to wait for the shutter to close and to set a light level afterwards by opening it again. As it seems the shortest timer interval is 1 second ("0.5" didn't work). Supporting smaller intervals would be great! This might be achieved by adding suffixes to the numbers (like usual on the Linux CLI). E.g. 1s for 1 second, 500ms for 500 milliseconds, 1d for 1 day, etc.

**Comment by tim-hellhake** [comment]
The next update should add support for decimal values like `0.5`.
It looks a bit weird though because the IntervalProperty only supports integer values.

**Comment by tim-hellhake** [comment]
Can you please test if it works?
I hope the whole event propagation is precise enough for this.

**Comment by rmeissn** [comment]
I'm sorry, in v1.3.1 a timer with less than 1s isn't working. The gateway auto-updated the add-on to v1.3.1 and I've 1) changed the existing timer to "0.5"s. This wasn't working, as the timer never reached the elapsed state. 2) I've added a new timer with "0.7"s which also wasn't working, as the timer never reached the elapsed state too.
If this matters: I'm using the latest docker version of the gateway.

**Comment by tim-hellhake** [comment]
Sorry, I think there was a misunderstanding.
Reading the title first, I assumed that you are using an interval, not a timer.
That's why I implemented it for intervals first.
I was just about to ask whether you actually need an interval when I noticed that you are talking about timers in the description.

The interval, as well as the timer, are designed to show the progress in the UI.
Therefore they have their own tick loop.
That makes it a bit harder to handle fractions of seconds correctly.
As I understood you, you need a precise sub-second one-shot timer.
I'll add a third option, which will do exactly that.

**Comment by tim-hellhake** [comment]
With the new update, there should be a new timer type called `precision timer`.
I tested it with a timer value of 0.7 seconds and got a deviation of 5 ms.
The values may vary on your system.

**Comment by tim-hellhake** [comment]
@rmeissn Did you have any to test it?

**Comment by tim-hellhake** [comment]
Did you have any to test it @rmeissn?

**Comment by rmeissn** [comment]
I've tested the precision timer and it works wonderful!. Many thanks for adding it!

I've noticed that normal timers have a "reset" action, which precision timers do not have. That is no problem to me, but I was confused when I noticed it for the first time.

**Comment by tim-hellhake** [comment]
> I've tested the precision timer and it works wonderful!. Many thanks for adding it!

I'm glad to hear that!
You're welcome :)
