### ISSUE TITLE
log filled with messages from interval

### ISSUE THREAD

**Issue by cjcorrigan** [tim-hellhake/timer-adapter#9]
Please reduce the 'chattiness' of the logging on intervals?

there's currently two updates per second
timer-adapter: setCachedValueAndNotify for property seconds from 1 to 1.5 for interval-c4c415fc99b87af0d464d777c94a1c73

In the Timer Addon  configuration, Log settings / Enable debug logs is not ticked

thanks :)

**Comment by tim-hellhake** [comment]
The problem is the log statement is produced outside the code of the timer adapter.

You can see the source [here](https://github.com/mozilla-iot/gateway-addon-node/blob/51fece28a1faaa47945aeaf554d5d17543738c1b/lib/property.js#L117).

I could try to deactivate logging in general, though.

**Comment by cjcorrigan** [comment]
I'll raise an issue in the Gateway project to see if there should be a choke on repeated messages there. Thanks :)
